### ISSUE TITLE
Send model API secure file transfer to Agile Monkeys

### ISSUE THREAD

**Issue by ndbolligerD3** [harvard-hbs-d3/d3-open-webui#10]

**Comment by Elmolesto** [comment]
@ndbolligerD3 @tflinthbs OpenAI is alredy configured in dev. You can selec which models of OpenAI you want to use from here:

<img width="1396" alt="Image" src="https://github.com/user-attachments/assets/9e9f6daa-e74c-454d-8b4e-2354b8deef3e" />


Additionally, if you’d like to hide any models, you can do so from this location:
https://openwebui.dev-digitaldatadesigninstitute.com/admin/settings

<img width="1252" alt="Image" src="https://github.com/user-attachments/assets/734e3bcf-f104-4b70-8743-f403afea7f87" />
