### ISSUE TITLE
Open WebUI can't handle file uploads bigger than 1MB

### ISSUE THREAD

**Issue by ndbolligerD3** [harvard-hbs-d3/d3-open-webui#2]

**Comment by ykumaar-d3** [comment]
- The current deployment (https://chat.digitaldatadesigninstitute.com/) is from this machine https://us-east-1.console.aws.amazon.com/ec2/home?region=us-east-1#InstanceDetails:instanceId=i-0414ba52590cde66d . 
- It is served similar to IPI as followed here https://github.com/harvard-hbs-d3/ipi-streamlit-app/blob/main/docs/domain_registration.md
- App is run following https://docs.openwebui.com/getting-started/quick-start#step-2-run-the-container

**Comment by Elmolesto** [comment]
This was tested on the dev environment with files up to 5MB. It's working correctly.
