### ISSUE TITLE
Continue Yogesh's work of creating a wrapper for Claude within AWS Bedrock

### ISSUE THREAD

**Issue by ndbolligerD3** [harvard-hbs-d3/d3-open-webui#3]
Current issues with the Claude wrapper:
- Files are not being shared to Claude properly. The chunking impacts the response from Claude.
- Making the AWS credentials passing more salient. Passing env variables for AWS access is not scalable.
- Known issue: Citations are not showing up on the chat ui when using claude

**Comment by Elmolesto** [comment]
We used LiteLLM to have a OpenAI api specification for Bedrock. This is configured in the admin.
