### ISSUE TITLE
o1-preview model doesn't work in Open WebUI

### ISSUE THREAD

**Issue by ndbolligerD3** [harvard-hbs-d3/d3-open-webui#5]

**Comment by tflinthbs** [comment]
@santigamo @Elmolesto @ndbolligerD3 I got an error when trying to use the model. It didn't run and displayed a red error message. This might be fixed in the new dev environment but I can't choose o1-preview to try it.

**Comment by santigamo** [comment]
@Elmolesto Could you enable o1-preview in the new environment?

**Comment by Elmolesto** [comment]
@santigamo @tflinthbs @ndbolligerD3 To add the `o1-preview` from OpenAI, we need to configure the API key and the model in OpenWebUI; could you give us an API key to do that? Thanks!!

**Comment by ndbolligerD3** [comment]
@Elmolesto I don't see o1-preview on https://openwebui.dev-digitaldatadesigninstitute.com/? Is it only on https://chat.digitaldatadesigninstitute.com/?

**Comment by tflinthbs** [comment]
@Elmolesto @ndbolligerD3 we're looking to make GPT-4o available, but I didn't see any of the Open AI models in Open Web UI Dev environment.

**Comment by Elmolesto** [comment]
> @Elmolesto @ndbolligerD3 we're looking to make GPT-4o available, but I didn't see any of the Open AI models in Open Web UI Dev environment.

Now it's working again. I'm investigating why the configuration has restarted.

**Comment by tflinthbs** [comment]
@Elmolesto @ndbolligerD3 is there an option to disable the Arena Model or set Claude as a default model? When I first start a chat I want to make sure it's the Claude model.

And is there an option to hide certain GPT models? I'll have to review the list and shorten the list if that's possible.
