### ISSUE TITLE
Open WebUI: Collection doesn't display all files uploaded

### ISSUE THREAD

**Issue by ndbolligerD3** [harvard-hbs-d3/d3-open-webui#6]
I uploaded 4 pdf files (under 1 MB) into collection: D3 Infra Resources. I only see 2 files. When I try to reupload the other missing 2, I get a duplicate file error. When I query/prompt, it refers to those "missing" 2 files.

**Comment by Elmolesto** [comment]
This issue couldn’t be reproduced in either local or dev environments.

**Comment by tflinthbs** [comment]
@ndbolligerD3 @Elmolesto I believe the issue can be reproduced as follows:

1. Add files to a collection.
2. Delete some of the files.
3. Run a prompt.

When you run the prompt, you’ll notice citations referencing the deleted files. The UI shows these files as deleted, but they still seem to be used for the prompts.

Could we test this to confirm? Let me know if you need more details!

**Comment by Elmolesto** [comment]
Hey @tflinthbs, I've tried this with a test collection with two files, and it's working correctly. Could you send me a video showing the problem or the files to test?
